# Generated by Django 2.0.3 on 2018-04-12 20:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoalbum',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
