# Generated by Django 2.0.3 on 2018-04-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20180412_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoAlbums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('xorder', models.IntegerField()),
            ],
            options={
                'ordering': ('xorder', '-year'),
            },
        ),
    ]
