# Generated by Django 2.0.3 on 2018-04-12 20:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advert_id', models.CharField(max_length=60)),
                ('company', models.CharField(max_length=60)),
                ('year', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=60)),
                ('source', models.CharField(max_length=90)),
                ('model', models.CharField(max_length=45)),
                ('date_created', models.DateTimeField(verbose_name=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-year', 'company'),
            },
        ),
    ]
